### PR TITLE
Update for Qt 6.11

### LINKED ISSUE #325: Doesn't build with QT 6.11.0 on linux
```
# github.com/mappu/miqt/qt6
In file included from gen_qstringconverter.cpp:4:
In file included from /usr/include/qt6/QtCore/QStringConverterBase:1:
/usr/include/qt6/QtCore/qstringconverter_base_deprecated.h:18:4: warning: "QStringConverterBase is not a public class and including "         "<QtCore/QStringConverterBase> is deprecated. The header will disappear"         " in Qt 7" [-W#warnings]
# github.com/mappu/miqt/qt6
In file included from gen_qstringconverter_base.cpp:2:
In file included from /usr/include/qt6/QtCore/QStringConverterBase:1:
/usr/include/qt6/QtCore/qstringconverter_base_deprecated.h:18:4: warning: "QStringConverterBase is not a public class and including "         "<QtCore/QStringConverterBase> is deprecated. The header will disappear"         " in Qt 7" [-W#warnings]
# github.com/mappu/miqt/qt6
gen_qvariant.cpp:36:10: fatal error: 'QVariantConstPointer' file not found
```

I had to downgrade to version 6.10 to be able to compile, but that broke parts of my system that needed version 6.11.

### PR DESCRIPTION
**Pull request by rcalixte**
This removes classes that either generate a warning or prevent builds against Qt 6.11:

```txt
# github.com/mappu/miqt/qt6
In file included from /usr/include/qt6/QtCore/QStringConverterBase:1,
                 from gen_qstringconverter.cpp:4:
/usr/include/qt6/QtCore/qstringconverter_base_deprecated.h:18:4: warning: #warning "QStringConverterBase is not a public class and including " "<QtCore/QStringConverterBase> is deprecated. The header will disappear" " in Qt 7" [-Wcpp]
   18 | #  warning "QStringConverterBase is not a public class and including " \
      |    ^~~~~~~
# github.com/mappu/miqt/qt6
In file included from /usr/include/qt6/QtCore/QStringConverterBase:1,
                 from gen_qstringconverter_base.cpp:2:
/usr/include/qt6/QtCore/qstringconverter_base_deprecated.h:18:4: warning: #warning "QStringConverterBase is not a public class and including " "<QtCore/QStringConverterBase> is deprecated. The header will disappear" " in Qt 7" [-Wcpp]
   18 | #  warning "QStringConverterBase is not a public class and including " \
      |    ^~~~~~~
# github.com/mappu/miqt/qt6
gen_qvariant.cpp:36:10: fatal error: QVariantConstPointer: No such file or directory
   36 | #include <QVariantConstPointer>
      |          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

```

* Closes #325

### CODE REVIEW

**Comment by nikitakurtash** [comment]
Confirmed, this fixes the build on both macOS and Windows with Qt 6.11. Thanks!

**Comment by karmakarmeghdip** [comment]
will this be merged?

**Comment by mappu** [comment]
LGTM. Awesome work as always @rcalixte !! And nice cleanup for the previous `QStringConverterBase` workarounds.

Thanks for your patience with the PR, I was just away on a nice holiday :desert_island: I'll catch up on the other PRs soon.
