### ISSUE TITLE
Qt 6.9 not compiling - QObjectData_dynamicMetaObject  invalid conversion from const

### ISSUE THREAD

**Issue by emad-elsaid** [mappu/miqt#194]
When trying to compile the webEngine example I'm getting an error:

```go
package main

import (
	"os"

	"github.com/mappu/miqt/qt"
	"github.com/mappu/miqt/qt6/webengine"
)

func main() {
	qt.NewQApplication(os.Args)
	w := webengine.NewQWebEngineView2()
	w.Load(qt.NewQUrl3("https://www.github.com/mappu/miqt"))
	w.Show()

	qt.QApplication_Exec()
}
```

my go.mod

```
module github.com/emad-elsaid/example

go 1.24.2

require github.com/mappu/miqt v0.9.0 // indirect
```

The error I'm getting:

```
➜ go run  -ldflags '-s -w' .
# github.com/mappu/miqt/qt6
gen_qobject.cpp: In function ‘QMetaObject* QObjectData_dynamicMetaObject(const QObjectData*)’:
gen_qobject.cpp:40:39: error: invalid conversion from ‘const QMetaObject*’ to ‘QMetaObject*’ [-fpermissive]
   40 |         return self->dynamicMetaObject();
      |                ~~~~~~~~~~~~~~~~~~~~~~~^~
      |                                       |
      |                                       const QMetaObject*
```

tried with dynamic linking:
```
CGO_ENABLED=1 go run -ldflags="-linkmode=external" .
# github.com/mappu/miqt/qt6
gen_qobject.cpp: In function ‘QMetaObject* QObjectData_dynamicMetaObject(const QObjectData*)’:
gen_qobject.cpp:40:39: error: invalid conversion from ‘const QMetaObject*’ to ‘QMetaObject*’ [-fpermissive]
   40 |         return self->dynamicMetaObject();
      |                ~~~~~~~~~~~~~~~~~~~~~~~^~
      |                                       |
      |                                       const QMetaObject*
```

**Comment by mappu** [comment]
It looks like `QObject::dynamicMetaObject` changed return type to const in Qt 6.9 released last week:
- #190 
- https://github.com/qt/qtbase/blob/6.9.0/src/corelib/kernel/qobject.h#L93

Miqt will need a small update in order to work with Qt 6.9. This can be easily fixed with genbindings/config-allowlist.go ApplyQuirks function to set the BecomesNonConstInVersion quirk for this method.

**Comment by rcalixte** [comment]
> Miqt will need a small update in order to work with Qt 6.9. This can be easily fixed with genbindings/config-allowlist.go ApplyQuirks function to set the BecomesNonConstInVersion quirk for this method.

This seems to be slightly more annoying to address:

```diff
diff --git a/qt6/gen_qobject.cpp b/qt6/gen_qobject.cpp
index 7c2a5635..b57d1418 100644
--- a/qt6/gen_qobject.cpp
+++ b/qt6/gen_qobject.cpp
@@ -36,7 +36,7 @@ void miqt_exec_callback_QObject_disconnectNotify(QObject*, intptr_t, QMetaMethod
 } /* extern C */
 #endif
 
-QMetaObject* QObjectData_dynamicMetaObject(const QObjectData* self) {
+const QMetaObject* QObjectData_dynamicMetaObject(const QObjectData* self) {
        return self->dynamicMetaObject();
 }
 
diff --git a/qt6/gen_qobject.h b/qt6/gen_qobject.h
index 47606a20..2597e069 100644
--- a/qt6/gen_qobject.h
+++ b/qt6/gen_qobject.h
@@ -48,7 +48,7 @@ typedef struct QTimerEvent QTimerEvent;
 typedef struct QVariant QVariant;
 #endif
 
-QMetaObject* QObjectData_dynamicMetaObject(const QObjectData* self);
+const QMetaObject* QObjectData_dynamicMetaObject(const QObjectData* self);
 void QObjectData_delete(QObjectData* self);
 
 QObject* QObject_new();
```

The return type is now `const` instead of the inverse. This worked for a local build of the examples against 6.9.0 on Arch. No other issues were encountered with the examples.

**Comment by rcalixte** [comment]
Feel free to assign this to me if you haven't started yet. I think I can get it done in an hour or two. Fortunately, this doesn't intersect with the existing const/non-const change. Once we start getting versions built against newer Qt bases, this should mitigate the issues. (And hopefully we don't need to deal with the intersection of these two... ever. 😅)

**Comment by mappu** [comment]
@emad-elsaid Can you please try `go get github.com/mappu/miqt@master` and confirm if that resolves the issue for you?

**Comment by emad-elsaid** [comment]
Thanks, I'll do that in the end of the day when I have access the machine

**Comment by rcalixte** [comment]
> [@mappu](https://github.com/mappu) I'm getting a different error:

This is something with how Qt is packaged for Arch. See #150 for more details. There is a workaround for the QQmlWebChannel header but QSctpServer and QSctpSocket are missing from the Qt 6 Network packages for Arch. This seems to be intentional but maybe check with upstream to be sure?

It would be great for Arch users if there could be a fix either here or upstream but this would be Arch-specific and not Linux-specific which makes a potential implementation more interesting.

**Comment by mappu** [comment]
Seems like these classes have been missing in Arch Linux since [at least 2019](https://forum.qt.io/topic/105530/qt-sctp-problem-can-not-define-a-qsctpsocket-qsctpserver-object/10).

A workaround would be to have genbindings move the two Sctp classes to a new subpackage, like was done with `cbor`. Probably only QSctpServer / QSctpClient are affected.

FYI @5k3105

**Comment by rcalixte** [comment]
Should this issue be closed in favor of #150 or a new one? Could it be tied into #185?

**Comment by mappu** [comment]
See also #151 / #159 for another (different) part of QNetwork that is not present in some distributions.

**Comment by emad-elsaid** [comment]
I see #199 is merged as a fix, but pulling master and retrying produce the same error, I made sure it's using the correct comment from go.sum
```
require github.com/mappu/miqt v0.9.1-0.20250412232210-862bd100f4be
```
I'm in no rush for a solution, just making sure we're aware it's not solved yet.

**Comment by mappu** [comment]
#199 is not merged yet. To try it early, run `go get github.com/mappu/miqt@miqt-archlinux-qt69`

**Comment by mappu** [comment]
OK, now it is merged :) It works for me in an Arch Linux container now with no warnings nor deprecation messages.

@emad-elsaid Can you please confirm the fix works for you too? You can update miqt via `go get github.com/mappu/miqt@master`.

**Comment by emad-elsaid** [comment]
Yup I confirm it compiled for me. the final example looks like this for reference: 
```go
package main

import (
	"os"

	qt "github.com/mappu/miqt/qt6"
	"github.com/mappu/miqt/qt6/webengine"
)

func main() {
	qt.NewQApplication(os.Args)
	w := webengine.NewQWebEngineView2()
	w.Load(qt.NewQUrl3("https://www.github.com/mappu/miqt"))
	w.Show()

	qt.QApplication_Exec()
}
```

**Comment by 5k3105** [comment]
Also works on my arch machine. This is really fantastic! Thanks a lot!
