### ISSUE TITLE
Doesn't build with QT 6.11.0 on linux

### ISSUE THREAD

**Issue by Tom5521** [mappu/miqt#325]
```
# github.com/mappu/miqt/qt6
In file included from gen_qstringconverter.cpp:4:
In file included from /usr/include/qt6/QtCore/QStringConverterBase:1:
/usr/include/qt6/QtCore/qstringconverter_base_deprecated.h:18:4: warning: "QStringConverterBase is not a public class and including "         "<QtCore/QStringConverterBase> is deprecated. The header will disappear"         " in Qt 7" [-W#warnings]
# github.com/mappu/miqt/qt6
In file included from gen_qstringconverter_base.cpp:2:
In file included from /usr/include/qt6/QtCore/QStringConverterBase:1:
/usr/include/qt6/QtCore/qstringconverter_base_deprecated.h:18:4: warning: "QStringConverterBase is not a public class and including "         "<QtCore/QStringConverterBase> is deprecated. The header will disappear"         " in Qt 7" [-W#warnings]
# github.com/mappu/miqt/qt6
gen_qvariant.cpp:36:10: fatal error: 'QVariantConstPointer' file not found
```

I had to downgrade to version 6.10 to be able to compile, but that broke parts of my system that needed version 6.11.

**Comment by rcalixte** [comment]
PR #322 is opened to resolve this.

**Comment by Tom5521** [comment]
Thank you!
