### ISSUE TITLE
QArrayData::needsDetach changed from const to non-const in Qt 6.7

### ISSUE THREAD

**Issue by pekim** [mappu/miqt#52]
`go run examples/helloworld/main.go` works fine.

However if I change the example's miqt import from `github.com/mappu/miqt/qt` to `github.com/mappu/miqt/qt6` the example fails to build.

```
# github.com/mappu/miqt/qt6
gen_qarraydata.cpp: In function ‘bool QArrayData_NeedsDetach(const QArrayData*)’:
gen_qarraydata.cpp:30:33: error: passing ‘const QArrayData’ as ‘this’ argument discards qualifiers [-fpermissive]
   30 |         return self->needsDetach();
      |                ~~~~~~~~~~~~~~~~~^~
In file included from /usr/include/qt6/QtCore/QArrayData:1,
                 from gen_qarraydata.cpp:1:
/usr/include/qt6/QtCore/qarraydata.h:76:10: note:   in call to ‘bool QArrayData::needsDetach()’
   76 |     bool needsDetach() noexcept
      |          ^~~~~~~~~~~
```

That was with gcc, but clang reported a similar error.

Am I overlooking something? Is it something environmental?

**Comment by mappu** [comment]
Thank you for trying MIQT and for your very clear issue report!

There is a version of `examples/helloworld` for Qt 6 also in `examples/libraries/qt6`. This builds cleanly for me with no warnings, using Debian 12 with system Qt 6.4, and also using the `docker/linux64-go1.19-qt6.4-dynamic.Dockerfile` in CI.

I had generated the bindings using Qt 6.4 headers.

- [In 6.4 through 6.7, QArrayData::needsDetach() is const](https://github.com/qt/qtbase/blob/6.4/src/corelib/tools/qarraydata.h#L69)
- But in 6.8 [it was changed to be non-const](https://github.com/qt/qtbase/blob/6.8/src/corelib/tools/qarraydata.h#L77)

This is the cause of the problem. MIQT is trying to call a function as if it is const, but Qt changed it to be non-const.

Qt is source-compatible when upgrading minor versions, so they are usually extremely avoidant of such changes. In this case, the change is probably correct based on the comment directly above. Because it was a header-only function, probably Qt did not consider this to be a source-breaking change.

But for MIQT (and probably for other bindings) it is a breaking change.

To solve this issue:

1. For now, a quick workaround is to `export CGO_CXXFLAGS=-fpermissive` to demote this const mismatch to only be a warning.
2. In the medium term, a better fix is if MIQT would either block generation of this function (is it really needed in MIQT...?) or patch this function to use a `#if QT_VERSION(` macro.
3. In the long term, the bindings should be generated for every minor Qt version and have `#ifdef` automatically applied.

**Comment by pekim** [comment]
> There is a version of examples/helloworld for Qt 6 also in examples/libraries/qt6.

Sorry, I hadn't spotted that example.

The const explanation all makes sense. Based on the error message I had thought about specifying the `permissive` option, but I stupidly forgot to give a go.

Thank you for the workaround. It does indeed address the problem for me, and downgrades the error to a warning. For reference I am using Fedora 40, with Qt 6 .7.2.

However, this then exposes another problem.

```
gen_qbitarray.cpp: In function ‘QBitArray* QBitArray_OperatorBitwiseXor(const QBitArray*)’:
gen_qbitarray.cpp:115:44: error: ‘const class QBitArray’ has no member named ‘operator~’; did you mean ‘operator=’?
  115 |         return new QBitArray(self->operator~());
      |                                            ^
      |                                            operator=
```

Looking in `/usr/include/qt6/QtCore/qbitarray.h` I see
```c++
#if QT_CORE_REMOVED_SINCE(6, 7)
    QBitArray operator~() const;
#endif
```
So I guess that it might be another 6.7 (or later) issue.

**Comment by pekim** [comment]
I just had a quick play, and if I comment out the `OperatorBitwiseXor` methods/functions in the relevant `.h`, `.cpp`, and `.go` files. That just exposes another problem. 

In `qt6/gen_qcoreevent.cpp` there is an include for `QDeferredDeleteEvent`. That header file is in `/usr/include/qt5/QtCore/QDeferredDeleteEvent` on Fedora 40. But is not present anywhere `/usr/include/qt6`.

This feels like it could be quite a deep rabbit hole. So I'm not going to pursue it any further for now.

**Comment by mappu** [comment]
After `QDeferredDeleteEvent` there were only a few more fixes needed :grin: 

I have updated the bindings-generator and built a version of MIQT that works on Fedora 40 / Qt 6.7 as well as older platforms. The MR is #53 and this configuration will be CI tested going forward.

**Comment by mappu** [comment]
I think everything's working now - please check out the latest master and see if it works for you too,

**Comment by pekim** [comment]
Yes, it works for me now. Thank you for sorting it out quickly.
